# Generated by Django 3.2.5 on 2021-10-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('note', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hungary', max_length=200, unique=True)),
                ('phone_code', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profile', models.CharField(max_length=250)),
                ('note', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.ManyToManyField(to='kesz.Address')),
                ('country', models.ForeignKey(default='Hungary', on_delete=django.db.models.deletion.CASCADE, to='kesz.country')),
                ('email', models.ManyToManyField(to='kesz.Email')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nameday', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.ManyToManyField(to='kesz.Address')),
                ('country', models.ForeignKey(default='Hungary', on_delete=django.db.models.deletion.CASCADE, to='kesz.country')),
                ('email', models.ManyToManyField(to='kesz.Email')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kesz.organization')),
                ('phone', models.ManyToManyField(related_name='persons', to='kesz.Phone')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kesz.position')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.ManyToManyField(to='kesz.Phone'),
        ),
    ]
