# Generated by Django 3.2.5 on 2021-10-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nameday',
        ),
    ]
